# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
plugins:
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed


# Site settings
title: enekoalonso.com
email: mail [at] enekoalonso [dot] com
description: > # this means to ignore newlines until "baseurl:"
  This is the personal site of Eneko Alonso, a software engineer in California.
  All content included and opinions expressed on this site are personal
  and do not represent any of his current or past employers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.enekoalonso.com" # the base hostname & protocol for your site

# Author
author:
  name: Eneko Alonso
  avatar: /media/eneko.jpg

# Social
twitter_username: eneko
github_username: eneko
stackoverflow_userid: 422288
stackoverflow_username: eneko-alonso


# Custom resources and categories
problem_categories: [linked-lists, aritmetic, logic-and-codes, binary-trees, multiway-trees, graphs, miscellaneous]
