name: Remote Update
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  writePost:
    runs-on: ubuntu-latest
    steps:
      - uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "test.md"
          FILE_DATA: ${{ github.event.inputs.name }}
      - run: |
          cat test.md
