name: Remote Update
on:
  workflow_dispatch:
    inputs:
      content:
        description: 'Content of the post'
        required: true
        default: 'Lorem ipsum dolore sit'
      filename:
        description: 'Filename for the post'
        required: true
        default: 'test.md'

jobs:
  writePost:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out
        uses: actions/checkout@master
      - name: Write File
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ${{ github.event.inputs.filename }}
          contents: ${{ github.event.inputs.content }}
          write-mode: overwrite
      - name: Dump File
        run: |
          cat test.md
      - name: Commit
        run: |
          git config --local user.email "eneko.alonso@gmail.com"
          git config --local user.name "Eneko Alonso"
          git add .
          git commit -m "Remote Update from GitHub Action"
      - name: Push
        run: |
          git push
