name: Remote Update
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  writePost:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out
        uses: actions/checkout@master
#       - name: Write File
#         uses: "finnp/create-file-action@master"
#         env:
#           FILE_NAME: "test.md"
#           FILE_DATA: ${{ github.event.inputs.name }}
      - name: Write File
        uses: DamianReeves/write-file-action
        with:
          path: "test.md"
          contents: ${{ github.event.inputs.name }}
          write-mode: overwrite
      - name: Dump File
        run: |
          cat test.md
      - name: Commit
#           git config --local user.email "action@github.com"
#           git config --local user.name "GitHub Action"
        run: |
          git config --local user.email "eneko.alonso@gmail.com"
          git config --local user.name "Eneko Alonso"
          git add .
          git commit -m "Remote Update from GitHub Action"
      - name: Push
        run: |
          git push
